easy_admin:
    site_name: 'Dashboard'

    design:
        menu:
          - { entity: 'UserEntreprise', icon: 'chevron-circle-right', permission: 'ROLE_ADMIN_COMPANY'}
          - { entity: 'Store', icon: 'chevron-circle-right', permission: ['ROLE_ADMIN_PLATEFORM']}
          - { entity: 'Company', icon: 'chevron-circle-right', permission: ['ROLE_ADMIN_PLATEFORM']}
          - { entity: 'User', icon: 'chevron-circle-right', permission: 'ROLE_ADMIN_PLATEFORM'}
          - { entity: 'UserStore', icon: 'chevron-circle-right', permission: ['ROLE_ADMIN_STORE']}
          - { entity: 'Publicity', icon: 'chevron-circle-right', permission: ['ROLE_ADMIN_PLATEFORM']}
          - { entity: 'Offer', icon: 'chevron-circle-right', permission: ['ROLE_ADMIN_PLATEFORM']}
          - { entity: 'Subscription', icon: 'chevron-circle-right', permission: ['ROLE_ADMIN_PLATEFORM']}
        templates:
          layout: 'admin/layout.html.twig' # templates/layout.html.twig
         
        brand_color: '#007bff'
        assets:
            css:
               - 'css/admin.css'
            js:
              - 'lib/mobile-nav/mobile-nav.js'
              - 'js/admin.js'
            favicon:
               path: 'images/default/favicon.ico'


    entities:
        # List the entity class name you want to manage
        Company:
            class: App\Entity\Company
            controller: App\Controller\Admin\Company\CompanyController
            disabled_actions: ['new','delete','edit']
            label: 'Entreprises'
            max_results: 20
            list:
              actions:
                - { name: 'changeStatus', label: 'Activer/Désactiver', icon: 'pencil' }



              fields:
                  - { property: 'name', label: 'Nom' }
                  - { property: 'siret', label: 'Siret' }
                  - { property: 'email', label: 'Email' }
                  - { property: 'phone', label: 'Phone' }
                  - { property: 'city', label: 'City' }
                  - { property: 'isValid', label: 'Active' }
        Store:
            class: App\Entity\Store
            controller: App\Controller\Admin\Store\StoreController
            label: 'Magasins'
            max_results: 20
            new:
                title:  'Créer Magasin'
            edit:
                title:  'Modifier Magasin'
            list:
              actions:
              - { name: 'new', label: 'Ajouter', icon: 'plus' }
              - { name: 'edit', icon: 'pencil', permission: 'ROLE_ADMIN_COMPANY' }
              - { name: 'delete', icon: 'close' , permission: 'ROLE_ADMIN_COMPANY'}
              fields:  
              - { property: 'reference', label: 'Code BV' }
              - { property: 'name', label: 'Nom' }
              - { property: 'email', label: 'Email' }
              - { property: 'phone', label: 'Téléphone' }
              - { property: 'country', label: 'Pays' , type: 'country' }
              - { property: 'city', label: 'Ville' }
            form:
              fields:
              - { type: 'group',  label: 'Informations Générale',icon: 'address-card-o', css_class: 'col-lg-6' }
              - { property: 'reference', label: 'Code BV' }
              - { property: 'name', label: 'Nom' , type_options: {  required: true , attr: {  maxlength: 255  } }}
              - { property: 'introduction', label: 'Introduction', type: 'textarea', type_options: {  required: true , attr: {  maxlength: 255  } }}
              - { property: 'description', label: 'Description', type: 'textarea', type_options: { attr: {  maxlength: 1000  } } }
              - { type: 'group', label: 'Adresse', icon: 'map-marker',  css_class: 'col-lg-6'}
              - { property: 'address_number',type: 'text', label: 'Numéro Adresse',  type_options: { required: true } }
              - { property: 'address_street', label: 'Rue', type: 'text' , type_options: { required: true } }
              - { property: 'address_post_code', label: 'Code postale', type: 'text' , type_options: { required: true } }
              - { property: 'country', label: 'Pays' , type: 'country' }
              - { property: 'city', label: 'Ville' }
              - { property: 'latitude', label: 'Latitude' }
              - { property: 'longitude', label: 'Longitude' }
              - { type: 'group',  label: 'Contact', icon: 'phone', css_class: 'col-lg-6'}
              - { property: 'email', label: 'Email' }
              - { property: 'phone', label: 'Téléphone' }
              - { type: 'group',  label: 'Attachement', icon: 'phone', css_class: 'col-lg-6'}
              - { property: 'imageFile', label: 'Photo du magasin', type: 'vich_image', upload_dir: 'public/images/company/' }
        Publicity:
            class: App\Entity\Publicity
            label: 'Publicité'
            new:
               title:  'Ajouter publicité'
            edit:
               title:  'Modifier la publicité'
            list:
               actions:
                 - { name: 'new', label: 'Ajouter', icon: 'plus' }
                 - { name: 'edit', icon: 'pencil', permission: 'ROLE_ADMIN_PLATEFORM' }
                 - { name: 'delete', icon: 'close' , permission: 'ROLE_ADMIN_PLATEFORM'}
               fields:
                 - { property: 'link', label: 'URL'}
                 - { property: 'filename', label: 'Image' }
            form:
               fields:
                 - { property: 'link', label: 'URl' }
                 - { property: 'imageFile', label: 'Image', type: 'vich_image', upload_dir: 'public/images/publicity/' }
        Offer:
          class: App\Entity\Offer
          label: 'Les offres'
          new:
            title:  'Ajouter un offre'
          edit:
            title:  'Modifier un offre'
          list:
            actions:
              - { name: 'new', label: 'Ajouter', icon: 'plus' }
              - { name: 'edit', icon: 'pencil', permission: 'ROLE_ADMIN_PLATEFORM' }
              - { name: 'delete', icon: 'close' , permission: 'ROLE_ADMIN_PLATEFORM'}
            fields:
              - { property: 'name', label: 'nom'}
              - { property: 'km', label: 'km' }
              - { property: 'nbServices', label: 'Nombre de services' }
              - { property: 'nbUsers', label: 'Nombre des utilisateurs' }
              - { property: 'price', label: 'Prix' }
          form:
            fields:
              - { property: 'name', label: 'nom'}
              - { property: 'km', label: 'km' }
              - { property: 'nbServices', label: 'nombre de services' }
              - { property: 'nbUsers', label: 'nombre des utilisateurs' }
              - { property: 'price', label: 'Prix' }
        Subscription:
          class: App\Entity\Subscription
          label: 'Les inscriptions'
          disabled_actions: ['new','edit','delete']
          list:
            actions:
              - { name: 'new', label: false, icon: 'plus' }

            fields:
              - { property: 'offer', label: 'offer'}
              - { property: 'company', label: 'company' }
              - { property: 'startDate', label: 'Date de début' }
              - { property: 'nbMonths', label: 'nombre des mois' }
              - { property: 'isExpired', label: 'status' }
        User:
            class: App\Entity\User
            controller: App\Controller\Admin\UserAdminController
            disabled_actions: ['delete']
            label: 'Utilisateurs'
            new:
                title:  'Ajouter un nouveau compte'
            list:
              actions:
              - { name: 'new', label: 'Ajouter', icon: 'plus'  }
              - { name: 'edit', icon: 'pencil' }
              - { name: 'delete', icon: 'close' }
              fields:  
              - { property: 'email', label: 'Email' }
              - { property: 'store', label: 'Magasin' }
              - { property: 'company', label: 'Entreprise' }
              - { property: 'type', label: 'Type' }
              - { property: 'profile', label: 'Prénom/Nom' }
              - { property: 'isValid', label: 'compte désactivé' }
            form:
              fields:
              - { property: 'email', label: 'Email' }
              -   property: 'roles'
                  label: 'Roles'
                  type: 'choice' 
                  type_options:
                     multiple: true
                     choices: { 'Admin platforme': 'ROLE_ADMIN_PLATEFORM','Admin Magasin': 'ROLE_ADMIN_STORE', 'Admin entreprise': 'ROLE_ADMIN_COMPANY', 'Utilisateur': 'ROLE_USER'}
              - { property: 'company', label: 'Entreprise' }
              - { property: 'store', label: 'Magasin' }


        UserEntreprise:
            class: App\Entity\User
            controller: App\Controller\Admin\UserEntrepriseController
            label: "Utilisateurs"
            disabled_actions: ['delete']
            new:
                title:  'Ajouter un nouveau compte'
            list:
              actions:
              - { name: 'new', label: 'Ajouter', icon: 'plus' }
              - { name: 'edit', icon: 'pencil' }
              - { name: 'delete', icon: 'close' }
              fields:
              - { property: 'profile', label: 'Prénom/Nom' }
              - { property: 'Email', label: 'Email' }
              - { property: 'type', label: 'Type' }
              - { property: 'isValid', label: 'compte désactivé' }
            form:
              fields:
              - { property: 'email', label: 'Email' }

            
        UserStore:
            class: App\Entity\User
            controller: App\Controller\Admin\UserStoreController
            label: "Utilisateurs"
            disabled_actions: ['delete']
            new:
                title:  'Ajouter un nouveau compte'
            list:
              actions:
              - { name: 'new', label: 'Ajouter', icon: 'plus' }
              - { name: 'edit', icon: 'pencil' }
              - { name: 'delete', icon: 'close' }
              fields:
              - { property: 'profile', label: 'Prénom/Nom' }
              - { property: 'Email', label: 'Email' }
              - { property: 'type', label: 'Type' }
              - { property: 'isValid', label: 'compte désactivé' }

           
            form:
              fields:
              - { property: 'email', label: 'Email' }
              - { property: 'type', label: 'Type' }
                     
             
