security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        users_in_database:
            entity:
                class: App\Entity\User
                property: email

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users_in_database
            pattern: ^/
            user_checker: App\Security\UserChecker
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            switch_user: true

            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: dashboard

            logout:
                path: security_logout
                target: security_login
                handlers: [App\EventListener\LogoutListener]

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/subscription, roles: ROLE_ADMIN_COMPANY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/homePage2, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/map, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/waitingValidation, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/cgu/accept, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login, allow_if: "!is_authenticated()"}
        - { path: ^/inscription, allow_if: "!is_authenticated()"}
        - { path: ^/forgottenPassword, allow_if: "!is_authenticated()"}
        - { path: ^/resetPassword, allow_if: "!is_authenticated()"}
        - { path: ^/newAccount, allow_if: "!is_authenticated()"}
        - { path: ^/confirmEmail, allow_if: "!is_authenticated()"}
        - { path: ^/search/store/, allow_if: "!is_authenticated()"}
        - { path: ^/be/contacted/by/, allow_if: "!is_authenticated()"}
        - { path: ^/external/company/, allow_if: "!is_authenticated()"}
        - { path: ^/be/contacted/list/, roles: ROLE_ADMIN_COMPANY}
        - { path: ^/, roles: ROLE_USER}

    role_hierarchy:
        #GLOBAL ROLES
        ROLE_ADMIN:    ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        #OUR ROLES
        ROLE_ADMIN_PLATEFORM: ROLE_SUPER_ADMIN
        ROLE_ADMIN_STORE: ROLE_ADMIN
        ROLE_ADMIN_COMPANY: ROLE_ADMIN
        ROLE_CONTRIBUTOR: ROLE_ADMIN