vich_uploader:
    db_driver: orm
    mappings:
        entreprise_logos:
            uri_prefix:         /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
        company_logos:
            uri_prefix:         /images/company
            upload_destination: '%kernel.project_dir%/public/images/company'