vich_uploader:
    db_driver: orm

    mappings:
        service_image:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        profile_image:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        entreprise_logos:
            uri_prefix:         /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
        company_logos:
            uri_prefix:         /images/company
            upload_destination: '%kernel.project_dir%/public/images/company'