vich_uploader:
    db_driver: orm

    mappings:
        service_image:
            uri_prefix:         /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        profile_image:
            uri_prefix:         /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        company_image:
            uri_prefix:         /images/company
            upload_destination: '%kernel.project_dir%/public/images/company'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        store_image:
            uri_prefix:         /images/store
            upload_destination: '%kernel.project_dir%/public/images/store'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        publicity_images:
            uri_prefix:         /images/publicity
            upload_destination: '%kernel.project_dir%/public/images/publicity'