vich_uploader:
    db_driver: orm

    mappings:
        service_image:
            uri_prefix:         /media/uploads/service
            upload_destination: '%kernel.project_dir%/public/uploads/service'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        profile_image:
            uri_prefix:         /media/uploads/profile
            upload_destination: '%kernel.project_dir%/public/media/uploads/profile'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        company_image:
            uri_prefix:         /media/uploads/company
            upload_destination: '%kernel.project_dir%/public/media/uploads/company'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        store_image:
            uri_prefix:         /media/uploads/store
            upload_destination: '%kernel.project_dir%/public/media/uploads/store'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        publicity_image:
            uri_prefix:         /media/uploads/publicity
            upload_destination: '%kernel.project_dir%/public/media/uploads/publicity'
        post_image:
            uri_prefix:         /media/uploads/post
            upload_destination: '%kernel.project_dir%/public/media/uploads/post'