monolog:
    channels: ['mailer', 'db'] # declare new channel for mails logs
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        mailer:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-mailer.log"
            level: debug
            channels: ["mailer"]
        db:
            type: service
            id: monolog.db_handler   #Name of service to use
            channels: ["db"]
